language: node_js
node_js:
  - '8'
env:
  global:
    # cozy-bot GITHUB_TOKEN
    - secure: ve8zUDAEVv3RwXngq4Dwb5ZKlFAUhyXZBJF6WDOlAvPqHT0mUbKhWZXJCsvkLl3j8/Zj1fYwSXFerhS7m5oRz48eO2aiKgEzjq/xnM+TkH8G5y7k+QZx6/ttuMRCpDoT9Z9vASuH/gurXLg3ACSQvsTGn1Di8iXbLSFEJBzMOpoG4kxS0SA2MucK201cT9h2yiH2Opej5Fk2200ziKPzmvGPMNjjNTujNS/7RD2Fgd70W+pcF6wkaGpd5geaV2lbtfvSX/OkRkMi7XiRlI7RWHfja5CXwoLaGXy2T/6mQgUpJjrl13JNwZrFecrv9+dTVqTdQ9MqtWPj3zO63p1ZXNFfbInUOn/zJfUFeucUr5p36JRJA7txcFOyyTDterhBynKkWd+UJurLaina3zFfeD4lnWFXuFKs3jcLcOGw44s35hSbgfYwxs5+P9CglwxmeShhKLJGuMJD2gkQDqE8ho7rk7ltyuAS9izyKeNOnyvr4WCUTQro5uGZzDZVnPFJbip8+kEoMIViGsTm1DD558f9aMV4jbgRWdBhrLYkWC3RI+3tEJaPwvOwormS2xonAYTrxS5jEF5w4VMr1oQH9OgMQ3bwWdUBRbz7aNN4SfHXxctfqcuIcVmVHHxXEpyrSrRAJlXECngCmjWhlw7N40vOW751LYR+xjgxXJ4oObs=
    # REGISTRY_TOKEN
    - secure: F4QbxtcDa1vY8WN+fim3U+70hB/2RuAX5dyg1/FmkdUxfxVLOBnwyFQ9j7eMB33asTopmveGOkJYCgADIOD9+9TVj4p4xJ0s+ngeFPgEHN6qwnV1ZoqlcofsWiMZc8AQn+9mqJtMfi9EIJFnprapUfmFs6/qC9z243e4boXuIrMMi1I06RuhFCdMEZB9yIGxl06VmkCeD3qs8yLDzn17ci9qqsBkx/0fi+SnBDJG7Tb9IVlBYykvrglwr2Qi6KE1DnvnDCHjNkuLh8n7eTxigkVMnIA7izv70Cd9K8jCgz1C32GkM5qQmg9OEhJrUDWvtOSERRCimglsuTWajs7ujCRNl8OGSZn7un7le9tFETEpFSV0Q+chUwvyluoOP3qx8yV2D3ZLDZ7NQWsly1OYsF8q6wZoODi+UkdEizJ5eTBpgazhGm090lMYvEr5Cq+k6kf2vmQuWQtujCS/4C5g1u40YUlWJZfNWTe0Q5Z2dvfet4gpdM8BKUNhYBJNejwuJW+NmLIOcumaocPWQEa3zTiVY/+vE0Yls2YqTOSJqbUdQ2CogMhQjY7SQxIe/XGVZxzGhgQ7nOMGZDL+49hgs2A0CurTLpQh290nMgA0mUHdsnRsHAMow7IsHhRggLFIdYFKqsjuMivgBrRLprXwNU+WLrPFaYS50QBc0ZokUF0=
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  - provider: script
    repo: konnectors/booking.com
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      branch: master
  - provider: script
    repo: konnectors/booking.com
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest yarn deploy && yarn cozyPublish
    on:
      branch: prod
  - provider: script
    repo: konnectors/booking.com
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest yarn deploy && yarn cozyPublish
    on:
      branch: prod
